apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Safarveisi/better-mlops.git'
    targetRevision: master
    path: manifests-argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
