- name: Check whether the target k8s namespace is defined
  ansible.builtin.assert:
    that:
      - k8s_namespace is defined
  tags: install-argocd

- name: Print the k8s namespace
  ansible.builtin.debug:
    msg: "The ArgoCD will be installed in {{ k8s_namespace }} namespace."
  tags: install-argocd

- name: Create a namespace for Argo CD
  kubernetes.core.k8s:
    name: "{{ k8s_namespace }}"
    state: present
    kind: Namespace
  tags: install-argocd

- name: Download ArgoCD's installation manifest file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: ./argo-cd-install.yaml
    mode: '0644'
  tags: install-argocd

- name: Apply the ArgoCD manifest file
  kubernetes.core.k8s:
    src: ./argo-cd-install.yaml
    state: present
    namespace: "{{ k8s_namespace }}"
  tags: install-argocd

- name: Sleep for 20 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 20
  tags: status-argocd

- name: Get a list of all pod objects
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ k8s_namespace }}"
  register: pod_list
  tags: status-argocd

- name: Check if all pods are in 'Running'
  ansible.builtin.set_fact:
    all_running: "{{ pod_list.resources | map(attribute='status.phase') | list | select('equalto', 'Running') | list | length == pod_list.resources | length }}"
  tags: status-argocd

- name: Print pod status and fail if not all are running
  ansible.builtin.debug:
    msg: >-
      {%- if all_running -%}
        All pods are in 'Running' state.
      {%- else -%}
        Not all pods are running!
      {%- endif -%}
  tags: status-argocd

- name: Fail play if not all pods are running
  ansible.builtin.fail:
    msg: "Not all pods are in 'Running' state."
  when: not all_running
  tags: status-argocd

- name: Flip argocd-server to a LoadBalancer in the argocd namespace
  kubernetes.core.k8s_json_patch:
    api_version: v1
    kind: Service
    name: argocd-server
    namespace: "{{ k8s_namespace }}"
    patch:
      - op: replace
        path: /spec/type
        value: LoadBalancer
  tags: expose-ui
